[package]
name = "rping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
pnet = { path="../libpnet", features = ["default", "std"]}
pnet_sys = "*"
rtnetlink = "0.9.1"
socket2 = "0.4.4"
tokio = { version = "1.19.2", features = ["full"]}

[[bin]]
name = "test"
path = "src/test.rs"
